#!/usr/bin/env node
/**
 * Build script: reads all source JSON from docs/data/ and generates
 * production files in the data/ folder.
 *
 * Source:  docs/data/  (categories, meta, distros, DEs, glossary, questions)
 * Output: data/       (data.js, questions.json)
 *
 * Usage: node docs/build_data.js
 */
const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'data');
const outDir = path.join(__dirname, '..', 'data');

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

function loadJSON(filename) {
  return JSON.parse(fs.readFileSync(path.join(srcDir, filename), 'utf8'));
}

// ── Load source data ────────────────────────────────────────────────

const categories = loadJSON('categories.json');
const meta = loadJSON('meta.json');
const deProfiles = loadJSON('de_profiles.json');
const glossary = loadJSON('glossary.json');
const leafDescs = loadJSON('descriptions.json');

// Load and merge all distro family files
const distroFiles = fs.readdirSync(srcDir)
  .filter(function (f) { return f.startsWith('distros_') && f.endsWith('.json'); });

var allDistros = [];
distroFiles.forEach(function (file) {
  var list = loadJSON(file);
  allDistros = allDistros.concat(list);
});
allDistros.sort(function (a, b) { return a.name.localeCompare(b.name); });

// Load and merge question category files
var questionsDir = path.join(srcDir, 'questions');
var questionsTree = {};
if (fs.existsSync(questionsDir)) {
  var qFiles = fs.readdirSync(questionsDir).filter(function (f) { return f.endsWith('.json'); });
  qFiles.forEach(function (file) {
    var catName = path.basename(file, '.json');
    questionsTree[catName] = JSON.parse(
      fs.readFileSync(path.join(questionsDir, file), 'utf8')
    );
  });
}

// ── Derive helper objects ───────────────────────────────────────────

var distroGroups = {};
allDistros.forEach(function (d) {
  if (!distroGroups[d.family]) distroGroups[d.family] = [];
  distroGroups[d.family].push(d.name);
});

var labelColors = {};
allDistros.forEach(function (d) { labelColors[d.name] = d.color; });

var descriptions = {};
allDistros.forEach(function (d) { descriptions[d.name] = d.description; });

var iconSources = {};
allDistros.forEach(function (d) { if (d.website) iconSources[d.name] = d.website; });

// Generate slug for each distro (used for icon filenames)
function toSlug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
}
var distroSlugs = {};
allDistros.forEach(function (d) {
  d.slug = toSlug(d.name);
  distroSlugs[d.name] = d.slug;
});

// ── Generate data.js ────────────────────────────────────────────────

var output = '// Auto-generated by docs/build_data.js — do not edit manually\n';
output += '// Source: docs/data/   Output: data/\n';
output += '// Rebuild: bun docs/build_data.js\n\n';

output += 'const resultsMapping = ' + JSON.stringify(categories, null, 2) + ';\n\n';
output += 'const categories = ' + JSON.stringify(meta.categories, null, 2) + ';\n\n';
output += 'const categoryTitles = ' + JSON.stringify(meta.categoryTitles, null, 2) + ';\n\n';
output += 'const subCategories = ' + JSON.stringify(meta.subCategories, null, 2) + ';\n\n';
output += 'const distros = ' + JSON.stringify(allDistros, null, 2) + ';\n\n';
output += 'const distroGroups = ' + JSON.stringify(distroGroups, null, 2) + ';\n\n';
output += 'const labelColors = ' + JSON.stringify(labelColors, null, 2) + ';\n\n';
output += 'const descriptions = ' + JSON.stringify(descriptions, null, 2) + ';\n\n';
output += 'const iconSources = ' + JSON.stringify(iconSources, null, 2) + ';\n\n';
output += 'const deProfiles = ' + JSON.stringify(deProfiles, null, 2) + ';\n\n';
output += 'const glossaryTerms = ' + JSON.stringify(glossary, null, 2) + ';\n\n';
output += 'const leafDescriptions = ' + JSON.stringify(leafDescs, null, 2) + ';\n\n';
output += 'const distroSlugs = ' + JSON.stringify(distroSlugs, null, 2) + ';\n\n';
output += 'function toSlug(name) {\n';
output += '  return name.toLowerCase().replace(/[^a-z0-9]/g, "_").replace(/_+/g, "_").replace(/^_|_$/g, "");\n';
output += '}\n\n';

// Scoring function
output += [
  '/**',
  ' * Score all distros against user results.',
  ' * Returns sorted array of { distro, score, maxScore, percent }',
  ' */',
  'function scoreDistros(userResults) {',
  '  var scored = distros.map(function(distro) {',
  '    var score = 0;',
  '    var maxScore = 0;',
  '    categories.forEach(function(cat) {',
  '      var userVal = userResults[cat];',
  '      if (!userVal) return;',
  '      var catScores = distro.scores[cat] || {};',
  '      var vals = Object.values(catScores);',
  '      var maxCatScore = vals.length > 0 ? Math.max.apply(null, vals) : 0;',
  '      maxScore += maxCatScore;',
  '      score += (catScores[userVal] || 0);',
  '    });',
  '    var percent = maxScore > 0 ? Math.round((score / maxScore) * 100) : 0;',
  '    return { distro: distro, score: score, maxScore: maxScore, percent: percent };',
  '  });',
  '  scored.sort(function(a, b) { return b.score - a.score; });',
  '  return scored;',
  '}',
  '',
  '/**',
  ' * Recommend a DE/WM based on user preferences and hardware.',
  ' */',
  'function recommendDE(userResults) {',
  '  var dePref = userResults.desktop_environment;',
  '  var hw = userResults.hardware;',
  '  var isConstrained = ["old_moderate", "ultra_light", "arm"].indexOf(hw) !== -1;',
  '  var deMap = {',
  '    "de_full_modern": isConstrained ? "Xfce" : "GNOME",',
  '    "de_full_traditional": isConstrained ? "Xfce" : "KDE Plasma",',
  '    "de_lightweight": isConstrained ? "LXQt" : "Xfce",',
  '    "de_minimal": isConstrained ? "IceWM" : "Openbox",',
  '    "de_tiling": "Hyprland",',
  '    "de_none": null',
  '  };',
  '  var deName = deMap[dePref] || null;',
  '  return deName ? (deProfiles[deName] || null) : null;',
  '}',
  ''
].join('\n');

fs.writeFileSync(path.join(outDir, 'data.js'), output);

// ── Generate questions.json ─────────────────────────────────────────

// Ensure questions are in the correct category order
var orderedQuestions = {};
meta.categories.forEach(function (cat) {
  if (questionsTree[cat]) {
    orderedQuestions[cat] = questionsTree[cat];
  }
});
fs.writeFileSync(
  path.join(outDir, 'questions.json'),
  JSON.stringify(orderedQuestions, null, 2) + '\n'
);

// ── Summary ─────────────────────────────────────────────────────────

console.log('Build complete:');
console.log('  data/data.js          (' + allDistros.length + ' distros, ' + Object.keys(glossary).length + ' glossary terms)');
console.log('  data/questions.json   (' + Object.keys(orderedQuestions).length + ' categories)');
console.log('Source files: ' + distroFiles.length + ' distro files from docs/data/');
